# Generated by Django 4.1.1 on 2022-09-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_original', models.ImageField(upload_to='images/')),
                ('image_webp', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('article', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('В наличии', 'В наличии'), ('Под заказ', 'Под заказ'), ('Ожидается поступление', 'Ожидается поступление'), ('Нет в наличии', 'Нет в наличии'), ('Не производится', 'Не производится')], max_length=21)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productimage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
